### ISSUE TITLE
admin access to RChain-API repo

### ISSUE THREAD

**Issue by dckc** [rchain-community/rchain-api#31]
@tschoffelen ,

@JoshOrndorff and I are moving the repo here, but the result is that we don't have a settings link so we can't rename it to lower case. I don't think we can add contributors either.

Help?

**Comment by tschoffelen** [comment]
Done! You should have admin access now.

**Comment by JoshOrndorff** [comment]
Confirmed, I am an admin and I' just renamed to lowercase. @dckc Can you confirm you're admin and move the issues?

**Comment by dckc** [comment]
confirmed. Thanks!

**Comment by tschoffelen** [comment]
Want me to remove https://github.com/rchain-community/rchain-api-wrong-droids?

**Comment by dckc** [comment]
Yes, though I'd rather you granted me access to do it.

**Comment by tschoffelen** [comment]
I've just made you co-owner of the organisation, so you should be able to delete repos now.
