### ISSUE TITLE
have travis check PRs

### ISSUE THREAD

**Issue by dckc** [rchain-community/rchain-api#47]
I think we had this working for https://github.com/JoshOrndorff/RChain-API

@JoshOrndorff feel free to re-assign to me if you'd rather not do this.

previously: https://github.com/rchain/rchain-api/issues/27

**Comment by dckc** [comment]
I suspect we need to do this again.

**Comment by tschoffelen** [comment]
Used the official IT solution of switching it off and on again, seems to be working fine! https://travis-ci.org/rchain-community/rchain-api
