### ISSUE TITLE
URIs not expressible in RHOCore

### ISSUE THREAD

**Issue by JoshOrndorff** [rchain-community/rchain-api#50]
Some relevant context is in #17 
An example of the problem this creates is
```
const rholangCode = rho`
new lookup(\`rho:registry:lookup\`), registerCh in {
  lookup!(\`URI\`, *registerCh)|

  for (registerForStatus <- registerCh){
    registerForStatus!(${req.params.name}, ${req.query.sig}, ${req.query.pubKey}, "bogusReturn")
  }
}
`.replace("URI", uri) //TODO Do this better
```

This is really more of a problem with the design of rhocore. I guess our options are.
1. Figure out a way to express uris in RHOCore and implement it
2. Figure out a work around so the hack is in the API rather than each dApp
3. Do nothing and let dApps write code like the example above.

**Comment by dckc** [comment]
I'm starting to lean toward expressing URIs in RHOCore using some constructor. There's a standard URL constructor that seems to work:

```
new URL('rho:id:wdwc36f4ixa6xacck3ddepmgueum7zueuczgthcqp6771kdu8jogm8')
```

Likewise byte arrays as `Uint8Array`.

And `GPrivate` from RhoTypes.

**Comment by dckc** [comment]
Supporting `GPrivate` in `toRholang` would be tricky... one way to do it would be to assume the rholang code to create is in a scope where the `GPrivate` is bound to a variable. We'd need an additional environment parameter that maps `GPrivate` values to variable names.

**Comment by dckc** [comment]
See:

 - 24326b4 extend RHOCore conversion to support URIs
 - e529a66 RHOCore: add bytes, private names

I could / should separate these from work on proxying and payment, but I haven't done so yet.

**Comment by dckc** [comment]
The environment stuff for `GPrivate` turned out to be not needed.
