### ISSUE TITLE
Expose feature the take RNode's pulse

### ISSUE THREAD

**Issue by JoshOrndorff** [rchain-community/rchain-api#6]
An end user may want to ping the connected RNode to make sure it is still alive, and update a dapp's UI or take other appropriate action when it is not. RNode should [export another method](https://github.com/JoshOrndorff/RChain-API/blob/master/rnodeAPI.js#L130) to do this. 

Possible implementation: Use the eval service to evaluate the stopped process (`0`) and if a response comes back, the node is alive.

Ideally the function would take no args and return bool.

**Comment by JoshOrndorff** [comment]
This issue was moved to rchain/rchain-api#10

**Comment by dckc** [comment]
`showBlocks` meets this need, no?

I updated the README to use `showBlocks` as the hello world example and moved `doDeploy` to a second example where I note that you need a validating node.
https://github.com/dckc/RChain-API/blob/rnode-0.9/README.md

**Comment by JoshOrndorff** [comment]
> `showBlocks` meets this need, no?

Totally.
