### ISSUE TITLE
NoNewDeploys,  While remote deploy to testnet0

### ISSUE THREAD

**Issue by dimworm** [rchain-community/rchain-api#68]
```
Error while creating block: NoNewDeploys
    at eitherSync (/root/oldhen/node_modules/rchain-api/src/rnodeAPI.js:170:11)
    at either (/root/oldhen/node_modules/rchain-api/src/rnodeAPI.js:162:12)
    at <anonymous>
```

**Comment by dckc** [comment]
I need more information to be able to reproduce the problem. Best practice is to report:

1. exactly what steps you took in sufficient detail that anyone else could take the same steps
2. what result you expected
3. what result you experienced

I only see part 3.

See, for example, [Mozilla's bug reporting guidelines](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines)

**Comment by dimworm** [comment]
I tried to deploy to node0.devnet.rchain-dev.tk via RChain API. And I got "NoNewDeploys" error.
Lately, I tried to deploy via rnode command line with --grpc-host, it also got the same error. So I think it's not the reason of API, it should be the first stage of testnet does not allow deploying from other nodes. 

I close this issue. Sorry to interrupt.

```
const express = require('express');
const bodyParser = require('body-parser');
const grpc = require('grpc')
const {RNode, RHOCore, keyPair, h2b, b2h, verify, SignDeployment} = require("rchain-api")

var host   = process.argv[2] ? process.argv[2] : "node0.devnet.rchain-dev.tk"
var port   = process.argv[3] ? process.argv[3] : 40401
var uiPort = process.argv[4] ? process.argv[4] : 8080
```
